// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQM_XgpJkbehbET6hObrSmKeNFc8h5BQ',
    appId: '1:515002784027:web:7a8a69a572a3e31e88dbbe',
    messagingSenderId: '515002784027',
    projectId: 'trip-planner-app-4315c',
    authDomain: 'trip-planner-app-4315c.firebaseapp.com',
    storageBucket: 'trip-planner-app-4315c.firebasestorage.app',
    measurementId: 'G-YXXCQG6V9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7JPkQeIZUpm1kkS8MgDxJLuPcBvUOow',
    appId: '1:515002784027:android:bc245d6fbe6192ca88dbbe',
    messagingSenderId: '515002784027',
    projectId: 'trip-planner-app-4315c',
    storageBucket: 'trip-planner-app-4315c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5Br3z7sFc9BBegeaeJkftWN3svlCfwQ',
    appId: '1:515002784027:ios:66e22b0693ba039488dbbe',
    messagingSenderId: '515002784027',
    projectId: 'trip-planner-app-4315c',
    storageBucket: 'trip-planner-app-4315c.firebasestorage.app',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO5Br3z7sFc9BBegeaeJkftWN3svlCfwQ',
    appId: '1:515002784027:ios:66e22b0693ba039488dbbe',
    messagingSenderId: '515002784027',
    projectId: 'trip-planner-app-4315c',
    storageBucket: 'trip-planner-app-4315c.firebasestorage.app',
    iosBundleId: 'com.example.tripPlanner',
  );
}
